server {
	listen 80;
	server_name _;
	server_tokens off;

    client_max_body_size 500M;

	location / {
		return 301 https://$server_name$request_uri;
	}	
}

server {
	server_name _;
	listen 443 ssl;
	server_tokens off;

    client_max_body_size 500M;

	location / {
		proxy_pass	http://blog:2368;
	        proxy_set_header    X-Real-IP $remote_addr;
	        proxy_set_header    Host      $host;
		proxy_set_header X-Forwarded-Proto $scheme;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	ssl_certificate     /etc/nginx/conf.d/ssl/fullchain.pem;
	ssl_certificate_key 	/etc/nginx/conf.d/ssl/privkey.pem;
}
